services:
  # 1. La Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: galponcito_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Interfaz visual para la Base de Datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: galponcito_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. El Backend (Node.js - Preparando el terreno)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: galponcito_backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - db
    volumes:
      # Para que los cambios en el código se reflejen en tiempo real
      - ./backend:/app
      - /app/node_modules

  # 4. El Frontend (React - Preparando el terreno)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: galponcito_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=import.meta.env.VITE_API_URL
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata: # Esto guarda los datos para que no se borren si apagas el contenedor
